### ISSUE TITLE
Mention pyserial in readme

### ISSUE THREAD

**Issue by frogshead** [BKPrecisionCorp/BK-8500-Electronic-Load#1]
Hi,
As there seems to be used external library pyserial for serial port handling, could you mention it in readme-file. 

as i just guessed to install it from pip like:
`
pip install serial 
`
it installs some serialization / deserialization  library. Maybe have a requirements.txt file inside your repo? 

Br,
/mikko/

**Comment by ryanroth79** [comment]
Hello /Mikko/,
Thank you for the suggestion. I will add it now.

-Ryan
